#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

RED="\033[0;31m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
NC="\033[0m"
TAB="    "

message="$(cat $1)"
requiredPattern='^(feat|fix|docs|style|refactor|test|chore|perf|ci|build|temp)\:\s[a-z& ]{2,48}$'
if ! [[ $message =~ $requiredPattern ]];
then
    echo ""
    echo -e "${RED}**************** Invalid commit message ****************${NC}"
    echo -e "commit message: ${RED}\"${message}\"${NC}"
    echo -e "correct format: ${GREEN}\"<type>: <subject>\"${NC}"
    echo -e "example: ${GREEN}\"feat: add new feature\"${NC}"
    echo ""
    echo -e "${YELLOW}type ${NC}"
    echo -e "${TAB}${YELLOW}feat${NC} \tA new feature."
    echo -e "${TAB}${YELLOW}fix${NC} \tA bug fix."
    echo -e "${TAB}${YELLOW}docs${NC} \tDocumentation only changes."
    echo -e "${TAB}${YELLOW}style${NC} \tChanges that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)."
    echo -e "${TAB}${YELLOW}refactor${NC} \tA code change that neither fixes a bug nor adds a feature."
    echo -e "${TAB}${YELLOW}test${NC} \tAdding missing tests or correcting existing ones."
    echo -e "${TAB}${YELLOW}chore${NC} \tChanges to the build process or auxiliary tools and libraries such as documentation generation."
    echo -e "${TAB}${YELLOW}perf${NC} \tA code change that improves performance."
    echo -e "${TAB}${YELLOW}ci${NC} \t\tChanges to your CI configuration files and scripts."
    echo -e "${TAB}${YELLOW}build${NC} \tChanges that affect the build system or external dependencies (example scopes gulp, broccoli, npm)."
    echo -e "${TAB}${YELLOW}temp${NC} \tTemporary commit that won\'t be included in your CHANGELOG."
    echo ""
    echo -e "${YELLOW}subject ${NC}"
    echo -e "${TAB}Summary of changes in present tense. Not capitalized. No period at the end."
    echo ""
    exit 1
fi

#write me a regex expression that allows for letters a-z, A-Z, numbers 0-9, spaces and ampersands
[[ "ci: hello & world" =~ ^(feat|fix|docs|style|refactor|test|chore|perf|ci|build|temp)\:\s[a-zA-z\s\&]*$ ]] && echo "yes"
# ^[(a-z0-9|\s|\&)]*$
[[ "&" =~ [a-zA-z\s\&]*$ ]] && echo "yes"