#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building before committing'

# run formatter before checking
yarn format

# check formatting just incase the formatter couldn't fix everything
yarn check-format ||
(
    echo '❌🖌️ Prettier Check Failed. Run yarn format, add changes and try commit again. 🎨❌';
    false;
)

# check typescript types
yarn check-types ||
(
    echo '❌⌨️ Failed Type check. Make the changes required above. 🧩❌'
    false;
)

echo '✅ You win this time... I am committing this now. ✅'